# Generated by Django 5.2 on 2026-05-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, default='', verbose_name='Текст статті')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Посилання на джерело')),
                ('source_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Джерело')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано до бази')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-pub_date', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='news_articl_categor_df3a9e_idx'), models.Index(fields=['-pub_date'], name='news_articl_pub_dat_eb3081_idx')],
            },
        ),
    ]
